Vectors and Vector Transposition


In [ ]:
import numpy as np

In [ ]:
# membuat vector x ukuran 3x1
x = np.array([[1],
              [2],
              [3]])
x

array([[1],
       [2],
       [3]])

In [ ]:
x.shape

(3, 1)

In [ ]:
# mencari tipe data vector x
tipe_x = x.dtype
tipe_x

dtype('int64')

In [ ]:
# mengakses elemen pertama
elemen_pertama = x[0, 0]
elemen_pertama

np.int64(1)

In [ ]:
# mencari tipe data elemen pertama
tipe_elemen = type(elemen_pertama)
tipe_elemen

numpy.int64

In [ ]:
x_t = x.T
x_t #mengtranspose

array([[1, 2, 3]])

In [ ]:
x_t.shape

(1, 3)

In [ ]:
# membuat vector y
y = np.array([[4],
              [5],
              [6]])
y

array([[4],
       [5],
       [6]])

In [ ]:
# mentranspose vector y
y_t = y.T
y_t

array([[4, 5, 6]])

In [ ]:
# mencari ukuran y transpose
ukuran_y_t = y_t.shape
ukuran_y_t

(1, 3)

In [ ]:
import tensorflow as tf

In [ ]:
# mencari vector x
x = tf.constant([[1],
                 [2],
                 [3]])
x

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [ ]:
# mencari ukuran
ukuran_x = x.shape
ukuran_x

TensorShape([3, 1])

In [ ]:
# menentukan tipe data
tipe_x = x.dtype
tipe_x

tf.int32

In [ ]:
# melihat elemen pertama
elemen_pertama = x[0, 0]
elemen_pertama

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
# mencari tipe elemen
tipe_elemen = elemen_pertama.dtype
tipe_elemen

tf.int32

In [ ]:
# membuat vector y
y = tf.constant([[4],
                 [5],
                 [6]])
y

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[4],
       [5],
       [6]], dtype=int32)>

In [ ]:
# mentranspose y
y_t = tf.transpose(y)
ukuran_y_t = y_t.shape
ukuran_y_t

TensorShape([1, 3])

In [7]:
import torch

In [ ]:
# membuat vector x menggunakan torch
x = torch.tensor([[1],
                  [2],
                  [3]])
x

tensor([[1],
        [2],
        [3]])

In [ ]:
# mencari ukuran
ukuran_x = x.shape
ukuran_x

torch.Size([3, 1])

In [ ]:
# menentukan tipe data
tipe_x = x.dtype

In [ ]:
# menentukan elemen pertama
elemen_pertama = x[0, 0]
elemen_pertama

tensor(1)

In [ ]:
# mencari tipe elemen
tipe_elemen = elemen_pertama.dtype
tipe_elemen

torch.int64

In [ ]:
# mentranspose
x_t = x.T
ukuran_x_t = x_t.shape
ukuran_x_t

torch.Size([1, 3])

In [ ]:
# membuat vector y
y = torch.tensor([[4],
                  [5],
                  [6]])
y

tensor([[4],
        [5],
        [6]])

In [ ]:
# mentranspose y
y_t = y.T
ukuran_y_t = y_t.shape
ukuran_y_t

torch.Size([1, 3])

Norms and Unit Vectors


In [2]:
import numpy as np

In [3]:
# vector x ukuran 3x1
x = np.array([[1],
              [2],
              [3]])
x

array([[1],
       [2],
       [3]])

In [5]:
(1**2 + 2**2 + 3**2)**(1/2)

3.7416573867739413

In [4]:
# L2 norm dari x
norm_x = np.linalg.norm(x)
norm_x

np.float64(3.7416573867739413)

In [11]:
torch.norm(torch.tensor([1, 2, 3.]))

tensor(3.7417)

In [ ]:
# vector v dengan elemen (3,4)
v = np.array([3, 4])
v


array([3, 4])

In [ ]:
# L2 norm dari v
norm_v = np.linalg.norm(v)
norm_v

np.float64(5.0)

In [ ]:
# menampilkan unit vector dari v
unit_v = v / norm_v
unit_v

array([0.6, 0.8])

In [ ]:
# menghitung panjang unit vector
panjang_unit_v = np.linalg.norm(unit_v)
panjang_unit_v

np.float64(1.0)

Basis, Orthogonal, and Orthonormal Vectors

In [ ]:
import numpy as np

In [ ]:
# membuat vector i dan j
i = np.array([1, 0])
j = np.array([0, 1])
i,j

(array([1, 0]), array([0, 1]))

In [ ]:
# membuktikan dot product
dot_ij = np.dot(i, j)
dot_ij

np.int64(0)

In [ ]:
# membuat vector v dan w
v = np.array([1, 2])
w = np.array([2, -1])
v,w


(array([1, 2]), array([ 2, -1]))

In [ ]:
# membuktikan dot product
dot_vw = np.dot(v, w)
dot_vw

np.int64(0)

Matrix Tensors

In [ ]:
import numpy as np

In [ ]:
# membuat matrix X ukuran 2x3
X = np.array([[1, 2, 3],
              [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# ukuran matrix
ukuran_X = X.shape
ukuran_X

(2, 3)

In [ ]:
# kolom pertama
kolom_pertama = X[:, 0]
kolom_pertama

array([1, 4])

In [ ]:
# baris kedua
baris_kedua = X[1, :]
baris_kedua

array([4, 5, 6])

In [ ]:
import torch

In [ ]:
# matrix X
X = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# ukuran
ukuran_X = X.shape
ukuran_X

torch.Size([2, 3])

In [ ]:
# kolom pertama
kolom_pertama = X[:, 0]
kolom_pertama

tensor([1, 4])

In [ ]:
# baris kedua
baris_kedua = X[1, :]
baris_kedua

tensor([4, 5, 6])

In [ ]:
import tensorflow as tf

In [ ]:
# matrix X
X = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
X

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# ukuran
ukuran_X = X.shape
ukuran_X

TensorShape([2, 3])

In [ ]:
# kolom pertama
kolom_pertama = X[:, 0]
kolom_pertama

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [ ]:
# baris kedua
baris_kedua = X[1, :]
baris_kedua

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

Generic Tensor Notation

In [ ]:
#torch.zeros(...) Fungsi dari PyTorch untuk membuat tensor berisi nol semua .Semua elemen dalam tensor akan bernilai 0
images_pt = torch.zeros([32, 28, 28, 3])
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

Perintah tersebut digunakan untuk:

Membuat data awal (dummy data),
Inisialisasi input untuk model deep learning,
Menyimpan kumpulan gambar dalam bentuk tensor

Exercises on Algebra Data Structures

In [12]:
import numpy as np

In [13]:
v = np.array([[25],
              [2],
              [-3],
              [-23]])
v

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [14]:
v.T

array([[ 25,   2,  -3, -23]])